pipeline {
    agent any
    stages {
        stage('Checkout sources') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/IzhevskBattleCityDev/codebattle-game-battlecity'
            }
        }

        stage('Build base image for codebattle-server') {
            steps {
                sh 'docker build --no-cache -t izhevsk-code-battle/codebattle-server-src -f dockerfile/codebattle-server .'
            }
        }
    }
}
