pipeline {
    agent any
    stages {
        stage('Checkout sources') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/IzhevskBattleCityDev/codebattle-game-battlecity'
            }
        }

/*      Needs to be run only once to create base image */
//        stage('Build base image for codebattle-server') {
//            steps {
//                sh 'docker build --no-cache -t izhevsk-code-battle/codebattle-server-src -f dockerfile/codebattle-server .'
//            }
//        }

        stage('Build Docker-image for battleship server') {
            steps {
                sh 'docker build --no-cache -t izhevsk-code-battle/codebattle-deploy-local -f dockerfile/codebattle-deploy-local .'
            }
        }

        stage('Stop running server') {
            steps {
                sh 'docker stop $(docker ps -a -q --filter ancestor=izhevsk-code-battle/codebattle-deploy-local --format="{{.ID}}")'
            }
        }

        stage('Run battleship') {
            steps {
                sh 'docker run -d -p 8080:8080 izhevsk-code-battle/codebattle-deploy-local:latest'
            }
        }

    }
}
